### ISSUE TITLE
Passing a non-existent directory to the `-p` argument causes a panic.

### ISSUE THREAD

**Issue by Daniel-Houston** [ribice/glice#21]
Passing a non-existent directory to the `-p` argument causes a panic.

```
> ls $GOPATH/src
github.com
> glice -p example.com/some/repo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13bdbfd]

goroutine 1 [running]:
main.getFolders.func1(0xc0000e40c0, 0x2e, 0x0, 0x0, 0x1559cc0, 0xc00015a000, 0x2, 0x2)
        /Users/dhouston/go/pkg/mod/github.com/ribice/glice@v0.0.0-20190502213737-321f539fdca1/main.go:115 +0x5d
path/filepath.Walk(0xc0000e40c0, 0x2e, 0xc0000c6900, 0x14c6aad, 0x1)
        /usr/local/Cellar/go/1.12.5/libexec/src/path/filepath/path.go:402 +0x6a
main.getFolders(0xc0000e4090, 0x2d, 0x0, 0x0, 0x0, 0x1, 0xc0000ca660)
        /Users/dhouston/go/pkg/mod/github.com/ribice/glice@v0.0.0-20190502213737-321f539fdca1/main.go:113 +0x175
main.main()
        /Users/dhouston/go/pkg/mod/github.com/ribice/glice@v0.0.0-20190502213737-321f539fdca1/main.go:81 +0x50b
```

By adding a check on line 114 of `main.go` for err != nil, I now get the following output
```main.go
    checkErr(filepath.Walk(fullPath+".", func(path string, info os.FileInfo, err error) error {                
         if err != nil {                                                                                        
             return err                                                                                         
         }
         ...                 
```

```
> glice -p example.com/some/repo
2019/07/18 11:46:25 lstat /Users/dhouston/go/src/example.com/some/repo/.: no such file or directory
```

Small change to make things a little more user friendly. Happy to submit a merge request

**Comment by ribice** [comment]
PR is very welcome!

**Comment by Daniel-Houston** [comment]
https://github.com/ribice/glice/pull/22

**Comment by Daniel-Houston** [comment]
Any update on getting that merged?
